services:
  bot:
    build: .
    ports:
      - "55555:55555"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      # - ENVIRONMENT=development
    restart: unless-stopped
    read_only: true
    cap_drop:
      - all
    tmpfs:
      - /tmp:mode=1733,exec
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    ulimits:
      nofile:   
        soft: 1024
        hard: 1024
